
export const MAIN_QUERY = 'ROOT_QUERY';
export const GROUPED_QUERY = 'GROUPED_QUERY';
export const VF_QUERY = 'VF_QUERY';
export const INCLUDE_VF_QUERY = 'INCLUDE_VF_QUERY';



const QUERY_INSTANCE_TYPES = {
  MAIN_QUERY: 'ROOT_QUERY',
  MAIN_MUTATION_CREATE: 'MAIN_MUTATION_CREATE',
  MAIN_MUTATION_UPDATE: 'MAIN_MUTATION_UPDATE',
  MAIN_MUTATION_DELETE: 'MAIN_MUTATION_DELETE',
  GROUPED_QUERY: 'GROUPED_QUERY',
  VF_QUERY: 'VF_QUERY',
  INCLUDE_VF_QUERY: 'INCLUDE_VF_QUERY'
};

export default QUERY_INSTANCE_TYPES;